language: python
python:
    - "3.5"
    - "3.6"
    - "3.7"
install:
    - pip install pipenv
    - pipenv install --dev --ignore-pipfile --skip-lock
    - pipenv run python setup.py develop
script:
  - pipenv run pycodestyle --show-source --show-pep8 experta
  - pipenv run coverage run $(pipenv run which py.test) -m 'not wip' -v tests/unit
after_success:
  - pipenv run codecov
